version: '3.8'

networks:
  spiffy-network:
    external: true

services:
  spiffy-gateway:
    container_name: spiffy-gateway
    restart: always
    image: caddy:latest
    volumes:
      - ${MODULE_ROOT:-.}/caddy.json:/etc/caddy/caddy.json
      - ${DATA_ROOT:-.}/caddy-config:/config
      - ${DATA_ROOT:-.}/caddy-data:/data
    ports:
      - "80:80"
      - "443:443"
    command: ["caddy", "run", "--config", "/etc/caddy/caddy.json"]
    networks:
      - spiffy-network